config/routes.rb
SampleApp::Application.routes.draw do
  root to: 'static_pages#home'
  resources :users do
    member do
      get :following, :followers
    end
    collection do
      get :tigers
    end    
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :password_resets 
  resources :mail_boxs, only: [:index, :show, :create, :destroy] do
    member do
      get  :send_email
      post :create_email
    end    
  end
  resources :category
  
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/search', to: 'static_pages#search', via: 'get'
  match '/messages', to: 'users#messages', via: 'get'
end

app/controllers/mail_boxs_controller.rb
class MailBoxsController < ApplicationController
  before_action :signed_in_user

  def index
    @outboxs = current_user.sent_messages
    @inboxs = current_user.received_messages
  end

  def show
    @message = current_user.messages.find(params[:id])
    @message.open
  end

  def destroy
    @message = current_user.messages.find(params[:id])
    if @message.destroy
      flash[:notice] = I18n.t("delete")
    else
      flash[:error] = I18n.t("fail")
    end
    redirect_to mail_boxs_path
  end

  def send_email
    @user = User.find(params[:id])
    render 'new_email'
  end

  def create_email
    @user = User.find(params[:id])
    topic = params[:acts_as_messageable_message][:topic]
    body = params[:acts_as_messageable_message][:body]    
    send_box(@user,topic,body)
  end

  def create
    @to = User.find_by_email(params[:acts_as_messageable_message][:to])
    topic = params[:acts_as_messageable_message][:topic]
    body = params[:acts_as_messageable_message][:body]
    if !@to.nil?
      send_box(@to,topic,body)
    else
      flash[:error] = I18n.t('email_null')
    end  
    redirect_to mail_boxs_path
  end

  def send_box(user,topic,body)
    if !topic.blank? and !body.blank?
      current_user.send_message(user, topic, body)
      UserMailer.send_boxs(user, topic, body).deliver
      flash[:success] = I18n.t("send_success")
    else
      flash[:error] = I18n.t("body_not_null")
    end
  end

end

app/helpers/mail_boxs_helper.rb
module MailBoxsHelper
 
 def get_box_user(user_id)
   @email = User.find(user_id).email
 end

 def status(value)
   flag = I18n.t('unread')
   if value == false
   	 flag
   else
     falg = I18n.t('read')
   end
 end

end

app/views/mail_boxs/_inbox_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t('send_user')%></th>
      <th><%= t('topic')%></th>
      <th><%= t('times')%></th>
      <th><%= t('status')%></th>          
    </tr>
  </thead>
  <% @inboxs.each do |m| %>
  <tbody>
    <tr>
      <td><%= get_box_user(m.sent_messageable_id) %></td>
      <td><%=link_to m.topic, mail_box_path(m.id) %></td>
      <td><%= m.created_at.strftime('%Y-%m-%d %H:%M') %></td>
      <td><%= status(m.opened) %></td> 
      <td><%= link_to t('delete'), mail_box_path(m.id),
                method: :delete,
                data: { confirm: t('your_sure') },
                class: "btn btn-mini btn-danger" %></td>           
    </tr>
  </tbody>
  <% end%>
</table>  

app/views/mail_boxs/_new_box.html.erb
<ul class="unstyled">
  <%= form_for ActsAsMessageable::Message.new, 
                  :url => { :controller => 'mail_boxs', 
                  :action => 'create', } do |f| %>
      <li><%= f.label :to, t(:to)%></li>
      <li><%= f.text_field :to, :class => "text_field", :placeholder => "example@example.com" %></li>

      <li><%= f.label :topic, t(:topic)%></li>
      <li><%= f.text_field :topic, :class => "text_field" %></li> 

      <li><%= f.label :body, t(:body) %></li>
      <li><%= f.kindeditor :body, :simple_mode => true, :width => 78, :height => 100 %></li>

      <li><%= f.submit t(:send), class: "btn btn btn-primary" %></li>
  <% end %>
</ul>

app/views/mail_boxs/_outbox_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t('send_user')%></th>
      <th><%= t('topic')%></th>
      <th><%= t('times')%></th>
    </tr>
  </thead>
  <% @outboxs.each do |m| %>
  <tbody>
    <tr>
      <td><%= get_box_user(m.received_messageable_id) %></td>
      <td><%= m.topic %></td>
      <td><%= m.created_at.strftime('%Y-%m-%d %H:%M') %></td>
      <td><%= link_to t('delete'), mail_box_path(m.id),
                method: :delete,
                data: { confirm: t('your_sure') },
                class: "btn btn-mini btn-danger" %></td>            
    </tr>
  </tbody>
  <% end %>
</table>  

app/views/mail_boxs/index.html.erb
<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab"><%= t('inbox')%>(<%= @inboxs.count() %>)</a></li>
    <li><a href="#tab2" data-toggle="tab"><%= t('outbox')%>(<%= @outboxs.count() %>)</a></li>
    <li><a href="#tab3" data-toggle="tab"><%= t('new_box')%></a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <%= render 'mail_boxs/inbox_list' %>
    </div>

    <div class="tab-pane" id="tab2">
      <%= render 'mail_boxs/outbox_list' %>
    </div>

    <div class="tab-pane" id="tab3">
      <%= render 'mail_boxs/new_box' %>
    </div>

  </div>
</div>

app/views/mail_boxs/new_email.html.erb
<ul class="unstyled">
  <%= form_for ActsAsMessageable::Message.new, 
                  :url => { :controller => 'mail_boxs', 
                  :action => 'create', } do |f| %>
      <li><%= f.label :to, t(:to)%></li>
      <li><%= f.text_field :to, :class => "text_field", :value => @user.email, :readonly => true %></li>

      <li><%= f.label :topic, t(:topic)%></li>
      <li><%= f.text_field :topic, :class => "text_field" %></li> 

      <li><%= f.label :body, t(:body) %></li>
      <li><%= f.kindeditor :body, :simple_mode => true, :width => 78, :height => 100 %></li>

      <li><%= f.submit t(:send), class: "btn btn btn-primary" %>
      <%= link_to t(:back), mail_boxs_path, class: "btn btn btn-info" %></li>
  <% end %>
</ul>

app/views/mail_boxs/show.html.erb
<dl class="dl-horizontal">
  <dt><%= t('topic')%>:</dt>
  <dd><%= @message.topic %></dd>

  <dt><%= t('send_user')%>:</dt>
  <dd><%= get_box_user(@message.sent_messageable_id) %></dd>  

  <dt><%= t('times')%>:</dt>
  <dd><%= @message.created_at.strftime('%Y-%m-%d %H:%M') %></dd>

  <dt><%= t('body')%>:</dt>
  <dd><%= sanitize @message.body %></dd>   
  <br />
  <dt><%= link_to t("back"), mail_boxs_path, class: "btn btn-mini btn-info" %>
      <%= link_to t("reply"), send_email_mail_box_path(@message.sent_messageable_id), 
        class: "btn btn-mini btn-info" %></dt>
</dl>