config/routes.rb
SampleApp::Application.routes.draw do
  root to: 'static_pages#home'
  resources :users do
    member do
      get :following, :followers
    end
    collection do
      get :tigers
    end    
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :password_resets 
  resources :mail_boxs, only: [:index, :show, :create, :destroy] do
    member do
      get  :send_email
      post :create_email
    end    
  end
  resources :category
  
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/search', to: 'static_pages#search', via: 'get'
  match '/messages', to: 'users#messages', via: 'get'
end

app/views/shared/_category.html.erb
<h2><%= t('category') %></h2>
<% Category.all.each do |c| %>
  <% if get_category(c.name).count()!=0 %>
    <div class="row-fluid">
      <div class="span4 offset3"><%= c.name %></div>
      <div class="span4"><%= get_category(c.name).count() %></div>
    </div>
  <% end %>  
<% end %>

app/views/shared/_datetime.html.erb
        <script language="JavaScript">  
            function startTime()     
            {     
                var today=new Date();//定义日期对象     
                var yyyy = today.getFullYear();//通过日期对象的getFullYear()方法返回年      
                var MM = today.getMonth()+1;//通过日期对象的getMonth()方法返回年      
                var dd = today.getDate();//通过日期对象的getDate()方法返回年       
                var hh=today.getHours();//通过日期对象的getHours方法返回小时     
                var mm=today.getMinutes();//通过日期对象的getMinutes方法返回分钟     
                var ss=today.getSeconds();//通过日期对象的getSeconds方法返回秒     
                // 如果分钟或小时的值小于10，则在其值前加0，比如如果时间是下午3点20分9秒的话，则显示15：20：09     
                MM=checkTime(MM);  
                dd=checkTime(dd);  
                mm=checkTime(mm);     
                ss=checkTime(ss);      
                var day; //用于保存星期（getDay()方法得到星期编号）  
                if(today.getDay()==0)   day   =   "星期日 "   
                if(today.getDay()==1)   day   =   "星期一 "   
                if(today.getDay()==2)   day   =   "星期二 "   
                if(today.getDay()==3)   day   =   "星期三 "   
                if(today.getDay()==4)   day   =   "星期四 "   
                if(today.getDay()==5)   day   =   "星期五 "   
                if(today.getDay()==6)   day   =   "星期六 "   
                document.getElementById('nowDateTimeSpan').innerHTML=yyyy+"-"+MM +"-"+ dd +" " + hh+":"+mm+":"+ss+"   " + day;     
                setTimeout('startTime()',1000);//每一秒中重新加载startTime()方法   
            }     
              
            function checkTime(i)     
            {     
                if (i<10){  
                    i="0" + i;  
                }     
                  return i;  
            }    
        </script>   
    <body onload="startTime()">  
      <h4>
        <font color="#00FF00;">
          <span id="nowDateTimeSpan" style=" margin-left: 0px;"></span>
        </font>      
      </h4>
    </body>  

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-error">
	The form contains <%= pluralize(object.errors.count, "error") %>.
	<ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
	  <%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>

  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>

  <span class="content"><%= feed_item.content %></span><br />
  
  <span class="timestamp">
	  <%= time_ago_in_words(feed_item.created_at) %>
  </span>

  <% if current_user?(feed_item.user) %>
	  <%= link_to t("delete"), feed_item, method: :delete,
	  data: { confirm: t("you_sure") },
	  title: feed_item.content,
    class: "btn btn-mini btn-danger" %>
  <% end %>
</li>

app/views/shared/_like.html.erb
<!-- JiaThis Button BEGIN -->
<div class="jiathis_style">
	<a class="jiathis_like_tsina"></a>
</div>
<script type="text/javascript" src="http://v3.jiathis.com/code_mini/jia.js" charset="utf-8"></script>
<!-- JiaThis Button END -->

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
	  <%= f.text_field :title, placeholder: t("new_blog_here") %>
	  <%= f.select :categ_name, Category.all.collect {|c| c.name } %>
		<%= f.kindeditor :content, :width => 852, :height => 350 %>
	</div>
	<%= f.submit t("new"), class: "btn btn-primary" %>
<% end %>

app/views/shared/_shareto.html.erb
<!-- JiaThis Button BEGIN -->
<div class="jiathis_style_24x24">
	<a class="jiathis_button_qzone"></a>
	<a class="jiathis_button_tsina"></a>
	<a class="jiathis_button_tqq"></a>
	<a class="jiathis_button_weixin"></a>
	<a class="jiathis_button_renren"></a>
	<!--a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank"></a-->
	<a class="jiathis_counter_style"></a>
</div>
<script type="text/javascript" src="http://v3.jiathis.com/code/jia.js" charset="utf-8"></script>
<!-- JiaThis Button END -->

app/views/shared/_statistics.html.erb
<h2>
	<%= t('web_count')%>
</h2>

<div class="row-fluid">
  <div class="span4 offset3"><%= t('people_count')%>:</div>
  <div class="span4"><%= usum %></div>
</div>
<div class="row-fluid">
  <div class="span4 offset3"><%= t('blog_count')%>:</div>
  <div class="span4"><%= msum %></div>
</div>
<div class="row-fluid">
  <div class="span4 offset3"><%= t('comment_count')%>:</div>
  <div class="span4"><%= csum %></div>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
  <div class="stats">
    <a href="<%= following_user_path(@user) %>">
      <strong id="following" class="stat">
        <%= @user.followed_users.count %>
      </strong>
      <%= t('following') %>
    </a>
    <a href="<%= followers_user_path(@user) %>">
      <strong id="followers" class="stat">
		<%= @user.followers.count %>
	  </strong>
	  <%= t('followers') %>
	</a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>" >
	<%= gravatar_for current_user %>
</a>
<h1>
	<%= current_user.name %>
</h1>
<span>
	<%= link_to t("view_my_profile"), current_user %>
</span>
<span>
	<%= pluralize(current_user.microposts.count, "micropost") %>
</span>