config/routes.rb
SampleApp::Application.routes.draw do
  root to: 'static_pages#home'
  resources :users do
    member do
      get :following, :followers
    end
    collection do
      get :tigers
    end    
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :password_resets 
  resources :mail_boxs, only: [:index, :show, :create, :destroy] do
    member do
      get  :send_email
      post :create_email
    end    
  end
  resources :category
  
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/search', to: 'static_pages#search', via: 'get'
  match '/messages', to: 'users#messages', via: 'get'
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 50000 }
  validates :title, presence: true, length: { maximum: 50 }
  validates :user_id, presence: true

  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end

  searchable do
    text :title, :categ_name
  end   
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create, :destroy]
  before_action :correct_user, only: [:destroy, :edit, :update ]

  def index
    redirect_to root_url
  end

  def show
  	@micropost = Micropost.find(params[:id])
  	@user = User.find(@micropost.user_id)
  end

  def new
  	@micropost = current_user.microposts.build
  end

  def create
  	@micropost = current_user.microposts.build(micropost_params)
  	if @micropost.save
  	  flash[:success] = I18n.t("micropost_created")
      @user = User.find(@micropost.user_id)
  	else
=begin
      @feed_items = []
  	  render 'static_pages/home'	
=end     
      render 'new'
    end
    render 'show'
  end

  def edit
    @micropost = Micropost.find(params[:id])
  end

  def update
    @user = User.find(@micropost.user_id)
    @micropost = Micropost.find(params[:id])
    if @micropost.update_attributes(micropost_params)
      flash[:success] = I18n.t("micropost_updated")
      render 'show'
    else
      redirect_to current_user
    end
  end

  def destroy
    @micropost.destroy
    redirect_to current_user
  end

  private
    def micropost_params
      params.require(:micropost).permit(:content, :title, :categ_name)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil? 
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  include StaticPagesHelper
  def wrap(content)
	sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  def comment_user(user_id)
    @user = User.find(user_id)
    @user.name

  end

  private

    def wrap_long_string(text, max_width = 30)
	  zero_width_space = "&#8203;"
	  regex = /.{1,#{max_width}}/
	  (text.length < max_width) ? text :
								  text.scan(regex).join(zero_width_space)
	end
end

app/views/microposts/_comment.html.erb
<div><%= t('comment_count')%>: <%= @micropost.comments.count()%>
     <%= t('number_comnet')%></div><br/>
<% @micropost.comments.each do |comment| %>
  <%= render partial:'comments/comment', locals: {comment:comment} %>
<% end %>

app/views/microposts/_micropost.html.erb
<table class="table table-hover">
<tr class="info">
  <td>
  <span class="content">
    <%= link_to micropost.title, micropost_path(micropost.id) %>
  </span><br />
  <span class="timestamp">
    <%= time_ago_in_words(micropost.created_at) %>
  </span>  
  <span><%= micropost.categ_name %></span>
  <span><%= t('comment_count')%>: <%= micropost.comments.count()%></span>
  <% if current_user?(micropost.user) %>
  <span>
    <%= link_to t("edit"), edit_micropost_path(micropost), class: "btn btn-mini btn-warning"%>
    <%= link_to t("delete"), micropost, method: :delete,
    data: { confirm: t("you_sure") },
    title: micropost.title, 
    class: "btn btn-mini btn-danger" %>
  </span>  
  <% end %>
  </td>
</tr>  
</table>
<style type="text/css">
span{
  margin-left: 20px;
}
</style>

app/views/microposts/edit.html.erb
<%= render 'shared/micropost_form' %>

app/views/microposts/new.html.erb
<%= render 'shared/micropost_form' %>

app/views/microposts/show.html.erb
<div class="pull-left">
  <h3><%= @micropost.title %></h3>
</div>
<table class="table table-hover">
  <td><%= t('author')%>: <%= @user.name %></td>
  <td><%= t('category')%>: <%= @micropost.categ_name %></td>
  <td>
    <%= t('created_time')%>: <%= @micropost.created_at.strftime('%Y-%m-%d %H:%M') %>
  </td>  
  <td class="pull-right">
    <%= render 'shared/shareto' %>
  </td>  
  <% if current_user?(@micropost.user) %>
    <td>
      <%= link_to t("edit"), edit_micropost_path(@micropost), class: "btn btn-mini  btn-info"%>
      <%= link_to t("delete"), @micropost, method: :delete,
                                              data: { confirm: t("your_sure") },
                                              title: @micropost.title,
                                              class: "btn btn-mini btn-danger" %>
    </td> 
  <% end %>
</table>
<p><%= @micropost.content.html_safe %></p><hr/>

<div class="comment_show">
  <%= render 'comment' %>
</div>

<%= form_for([ @micropost, @micropost.comments.build], remote: true) do |f| %>
  <% if signed_in? %>
    <%= f.kindeditor :body, :width => 853, :height => 100 %>
    <%= f.submit t("submit_comment"), class: "btn btn-primary" %>
  <% else %>
    <%= t('comment_login')%> <%= link_to t("singin"), signin_path %>
  <% end %>  
<% end %>