config/routes.rb
SampleApp::Application.routes.draw do
  root to: 'static_pages#home'
  resources :users do
    member do
      get :following, :followers
    end
    collection do
      get :tigers
    end    
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :password_resets 
  resources :mail_boxs, only: [:index, :show, :create, :destroy] do
    member do
      get  :send_email
      post :create_email
    end    
  end
  resources :category
  
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/search', to: 'static_pages#search', via: 'get'
  match '/messages', to: 'users#messages', via: 'get'
end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom navbar-inverse">
<div class="container">
  <ul class="nav">
    <li><span><%= link_to t("chinese"), :controller => controller.controller_name,
              :action => controller.action_name, :locale => "zh" %></span> 
    </li>
    <li><span><%= link_to t("english"), :controller => controller.controller_name,
              :action => controller.action_name, :locale => "en" %></span>
    </li>
    <li><span><%= link_to t("contact"), contact_path %></span></li>  
  </ul>
</div>  
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="navbar-inner">
  <div class="container" style="width: 1200px;">
    <%= link_to image_tag("logo.png", alt: "Logo"), root_path, id: "logo" %>
    <nav>
      <ul class="nav pull-right header-dd" style="margin-top: 25px;">
        <!--li><%= link_to t("home"), root_path %></li-->
        <% if signed_in? %>
        <li><%= link_to t("new_micropost"), new_micropost_path %></li>
          <li id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t('account') %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
          <% if current_user.admin? %>
            <li><%= link_to t("users"), users_path %></li>
            <li><%= link_to t("category_set"), category_index_path %></li>
            <li class="divider"></li>
          <% end %>
          <li><%= link_to t("profile"), current_user %></li>
          <li><%= link_to t('edit_user'), edit_user_path(current_user) %></li> 
          <li><%= link_to t("inbox"), mail_boxs_path %></li>
          <li class="divider"></li>
          <li>
            <%= link_to t("logout"), signout_path, method: "delete" %>
          </li>
        <% else %> 
          <li><%= link_to t("singin"), signin_path %></li>
          <li><%= link_to t("singup"), signup_path %></li>
        <% end %>

      </ul>	
    </nav>
  </div>
</div>
</header>

app/views/layouts/_home_page.html.erb
<div class="center home">
 <table style="margin-left: auto; margin-right: auto;">
    <td>
      <div class="ih-item square colored effect9 right_to_left">
        <a href="#">
          <div class="img"><%= image_tag("1.jpg") %></div>
          <div class="info">
            <div class="info-back">
              <h3>Heading here</h3>
                <p>Description goes here</p>
              </div>
            </div>
          </a>
        </div>
    </td>
    <td>
      <div class="ih-item square colored effect7">
        <a href="#">
          <div class="img"><%= image_tag("2.jpg") %></div>
          <div class="info">
          <div class="info-back">
            <h3>Heading here，Heading here，here</h3>
            <p>Description goes here</p>
          </div>
      </div></a></div>
    </td>
    <td>
      <div class="ih-item square colored effect7">
        <a href="#">
          <div class="img"><%= image_tag("3.jpg") %></div>
          <div class="info">
            <div class="info-back">
              <h3>Heading here</h3>
                <p>Description goes here</p>
              </div>
            </div>
          </a>
        </div>
    </td>  
    <td>
      <div class="ih-item square colored effect9 left_to_right">
        <a href="#">
          <div class="img"><%= image_tag("4.jpg") %></div>
          <div class="info">
            <div class="info-back">
              <h3>Heading here</h3>
                <p>Description goes here</p>
              </div>
            </div>
          </a>
        </div>
    </td>         
</table>
 <!--table style="margin-left: auto; margin-right: auto;">
    <td>
      <div class="ih-item square colored effect9 right_to_left">
        <a href="#">
          <div class="img"><%= image_tag("1.jpg") %></div>
          <div class="info">
            <div class="info-back">
              <h3>Heading here</h3>
                <p>Description goes here</p>
              </div>
            </div>
          </a>
        </div>
    </td>
    <td>
      <div class="ih-item square colored effect9 top_to_bottom">
        <a href="#">
          <div class="img"><%= image_tag("2.jpg") %></div>
          <div class="info">
          <div class="info-back">
            <h3>Heading here，Heading here，here</h3>
            <p>Description goes here</p>
          </div>
      </div></a></div>
    </td>
    <td>
      <div class="ih-item square colored effect9 top_to_bottom">
        <a href="#">
          <div class="img"><%= image_tag("3.jpg") %></div>
          <div class="info">
            <div class="info-back">
              <h3>Heading here</h3>
                <p>Description goes here</p>
              </div>
            </div>
          </a>
        </div>
    </td>  
    <td>
      <div class="ih-item square colored effect9 left_to_right">
        <a href="#">
          <div class="img"><%= image_tag("4.jpg") %></div>
          <div class="info">
            <div class="info-back">
              <h3>Heading here</h3>
                <p>Description goes here</p>
              </div>
            </div>
          </a>
        </div>
    </td>         
</table-->
</div>





app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta property="qc:admins" content="35064156530216760527351006375" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container" style="width: 1200px;">
    <div class="row-fluid">
      <div class="span9">
        <div class="well">
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
          <%= yield %>
        </div>
      </div>
      <div class="span3">   
        <div class="well">
          <%= render 'shared/statistics' %>
        </div>
      </div>  
    </div>
    <!--%= debug(params) if Rails.env.development? %-->
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta property="qc:admins" content="35064156530216760527351006375" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container" style="width: 1200px;">
    <div class="row-fluid">
      <div class="span9">
        <div class="well">
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
          <%= yield %>
        </div>
      </div>
      <div class="span3">   
        <div class="well">
          <%= render 'shared/datetime' %>
        </div>        
        <div class="well">
          <%= render 'shared/statistics' %>
        </div>
        <div class="well">
          <%= render 'shared/category' %>
        </div>        
      </div>  
    </div>
    <!--%= debug(params) if Rails.env.development? %-->
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta property="qc:admins" content="35064156530216760527351006375" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container" >
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
    <!--%= debug(params) if Rails.env.development? %-->
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>